name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    environment: dev
    steps:
      - uses: actions/checkout@v3.3.0
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GENTLE_MUSHROOM_0602EAE03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "" # Built app content directory - optional
          api_build_command: "rm -rf $SOURCE_DIR/node_modules/@next/swc-* && rm -rf $SOURCE_DIR/.next/cache"
          ###### End of Repository/Build Configurations ######
        env:
          NEXT_PUBLIC_SANITY_DATASET: dev
          NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_ID }}
          SANITY_API_TOKEN: ${{ secrets.SANITY_API_TOKEN }}
          NEXT_PUBLIC_SANITY_API_READ_TOKEN: ${{ secrets.NEXT_PUBLIC_SANITY_API_READ_TOKEN }}
          NEXT_PUBLIC_SANITY_STUDIO_PREVIEW_SECRET: ${{ secrets.NEXT_PUBLIC_SANITY_STUDIO_PREVIEW_SECRET }}
          NEXT_PUBLIC_SANITY_STUDIO_REVALIDATE_SECRET: ${{ secrets.NEXT_PUBLIC_SANITY_STUDIO_REVALIDATE_SECRET }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GENTLE_MUSHROOM_0602EAE03 }}
          action: "close"
